[2024-10-10T04:33:25.302-0400] {processor.py:186} INFO - Started process (PID=463) to work on /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:33:25.359-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/openai_Pipeline.py for tasks to queue
[2024-10-10T04:33:25.424-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:33:25.392-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:33:34.932-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:33:34.637-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:33:35.034-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:33:37.408-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/openai_Pipeline.py took 13.480 seconds
[2024-10-10T04:34:14.014-0400] {processor.py:186} INFO - Started process (PID=465) to work on /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:34:14.339-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/openai_Pipeline.py for tasks to queue
[2024-10-10T04:34:15.407-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:34:15.310-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:34:22.560-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:34:22.450-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:34:22.576-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:34:24.593-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/openai_Pipeline.py took 11.513 seconds
[2024-10-10T04:34:55.746-0400] {processor.py:186} INFO - Started process (PID=468) to work on /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:34:55.753-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/openai_Pipeline.py for tasks to queue
[2024-10-10T04:34:55.786-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:34:55.784-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:34:57.790-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:34:57.771-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:34:57.792-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:34:58.034-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/openai_Pipeline.py took 2.329 seconds
[2024-10-10T04:35:28.294-0400] {processor.py:186} INFO - Started process (PID=471) to work on /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:35:28.297-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/openai_Pipeline.py for tasks to queue
[2024-10-10T04:35:28.301-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:35:28.299-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:35:28.496-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:35:28.494-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:35:28.497-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:35:28.550-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/openai_Pipeline.py took 0.291 seconds
[2024-10-10T04:35:58.718-0400] {processor.py:186} INFO - Started process (PID=474) to work on /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:35:58.720-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/openai_Pipeline.py for tasks to queue
[2024-10-10T04:35:58.723-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:35:58.722-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:35:58.860-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:35:58.857-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:35:58.861-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:35:58.914-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/openai_Pipeline.py took 0.210 seconds
[2024-10-10T04:36:29.269-0400] {processor.py:186} INFO - Started process (PID=477) to work on /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:36:29.271-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/openai_Pipeline.py for tasks to queue
[2024-10-10T04:36:29.274-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:36:29.273-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:36:29.399-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:36:29.397-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:36:29.400-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:36:29.427-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/openai_Pipeline.py took 0.188 seconds
[2024-10-10T04:36:59.986-0400] {processor.py:186} INFO - Started process (PID=480) to work on /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:36:59.989-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/openai_Pipeline.py for tasks to queue
[2024-10-10T04:36:59.998-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:36:59.993-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:37:00.198-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:37:00.195-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:37:00.198-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:37:00.236-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/openai_Pipeline.py took 0.266 seconds
[2024-10-10T04:37:30.809-0400] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:37:30.812-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/openai_Pipeline.py for tasks to queue
[2024-10-10T04:37:30.815-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:37:30.814-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:37:30.972-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:37:30.970-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:37:30.972-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:37:31.013-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/openai_Pipeline.py took 0.220 seconds
[2024-10-10T04:38:01.385-0400] {processor.py:186} INFO - Started process (PID=486) to work on /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:38:01.389-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/openai_Pipeline.py for tasks to queue
[2024-10-10T04:38:01.392-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:38:01.391-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:38:01.549-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:38:01.547-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:38:01.550-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:38:01.588-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/openai_Pipeline.py took 0.243 seconds
[2024-10-10T04:38:32.198-0400] {processor.py:186} INFO - Started process (PID=489) to work on /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:38:32.204-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/openai_Pipeline.py for tasks to queue
[2024-10-10T04:38:32.211-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:38:32.208-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:38:32.350-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:38:32.348-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:38:32.351-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:38:32.396-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/openai_Pipeline.py took 0.215 seconds
[2024-10-10T04:39:02.986-0400] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:39:02.989-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/openai_Pipeline.py for tasks to queue
[2024-10-10T04:39:02.992-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:39:02.991-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:39:03.123-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:39:03.121-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:39:03.123-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/openai_Pipeline.py
[2024-10-10T04:39:03.170-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/openai_Pipeline.py took 0.203 seconds
[2024-10-10T04:41:59.423-0400] {processor.py:186} INFO - Started process (PID=49) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:41:59.428-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:41:59.537-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:41:59.536-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:42:00.166-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:42:00.149-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:42:00.221-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:42:00.370-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.978 seconds
[2024-10-10T04:42:30.947-0400] {processor.py:186} INFO - Started process (PID=52) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:42:30.952-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:42:30.976-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:42:30.973-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:42:32.452-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:42:32.449-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:42:32.453-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:42:32.537-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 1.638 seconds
[2024-10-10T04:43:02.746-0400] {processor.py:186} INFO - Started process (PID=55) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:43:02.747-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:43:02.758-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:43:02.756-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:43:04.115-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:43:04.110-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:43:04.116-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:43:04.150-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 1.448 seconds
[2024-10-10T04:43:35.235-0400] {processor.py:186} INFO - Started process (PID=58) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:43:35.236-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:43:35.241-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:43:35.240-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:43:35.650-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:43:35.649-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:43:35.651-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:43:35.668-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.446 seconds
[2024-10-10T04:44:06.049-0400] {processor.py:186} INFO - Started process (PID=61) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:44:06.053-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:44:06.058-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:44:06.057-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:44:06.661-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:44:06.658-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:44:06.662-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:44:06.721-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.701 seconds
[2024-10-10T04:44:37.203-0400] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:44:37.206-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:44:37.213-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:44:37.212-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:44:37.597-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:44:37.596-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:44:37.597-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:44:37.611-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.427 seconds
[2024-10-10T04:45:25.230-0400] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:45:25.244-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:45:25.271-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:45:25.270-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:45:25.938-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:45:25.934-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:45:25.939-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:45:26.032-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.847 seconds
[2024-10-10T04:45:56.843-0400] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:45:56.848-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:45:56.871-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:45:56.867-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:45:58.236-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:45:58.234-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:45:58.237-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:45:58.266-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 1.463 seconds
[2024-10-10T04:46:28.968-0400] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:46:28.977-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:46:28.982-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:46:28.981-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:46:29.800-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:46:29.795-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:46:29.800-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:46:29.835-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.880 seconds
[2024-10-10T04:48:14.408-0400] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:48:14.417-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:48:14.465-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:48:14.464-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:48:15.226-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:48:15.218-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:48:15.228-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:48:15.348-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.969 seconds
[2024-10-10T04:48:46.372-0400] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:48:46.375-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:48:46.415-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:48:46.407-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:48:47.440-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:48:47.439-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:48:47.441-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:48:47.477-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 1.138 seconds
[2024-10-10T04:49:17.849-0400] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:49:17.851-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:49:17.856-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:49:17.855-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:49:18.320-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:49:18.318-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:49:18.320-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:49:18.348-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.510 seconds
[2024-10-10T04:49:48.795-0400] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:49:48.797-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:49:48.801-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:49:48.800-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:49:49.178-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:49:49.177-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:49:49.179-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:49:49.197-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.412 seconds
[2024-10-10T04:50:19.346-0400] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:50:19.348-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:50:19.353-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:50:19.352-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:50:19.723-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:50:19.722-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:50:19.724-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:50:19.741-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.406 seconds
[2024-10-10T04:50:50.357-0400] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:50:50.359-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:50:50.364-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:50:50.363-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:50:50.788-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:50:50.786-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:50:50.789-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:50:50.853-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.523 seconds
[2024-10-10T04:51:21.514-0400] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:51:21.517-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:51:21.522-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:51:21.521-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:51:21.871-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:51:21.870-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:51:21.871-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:51:21.900-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.396 seconds
[2024-10-10T04:51:52.095-0400] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:51:52.101-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:51:52.108-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:51:52.107-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:51:52.475-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:51:52.474-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:51:52.476-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:51:52.542-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.461 seconds
[2024-10-10T04:52:22.808-0400] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:52:22.810-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:52:22.815-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:52:22.814-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:52:22.925-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:52:22.924-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:52:22.926-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:52:22.960-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.160 seconds
[2024-10-10T04:52:53.445-0400] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:52:53.446-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:52:53.450-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:52:53.449-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:52:53.580-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:52:53.578-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:52:53.581-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:52:53.621-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.185 seconds
[2024-10-10T04:53:24.167-0400] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:53:24.171-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:53:24.175-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:53:24.174-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:53:24.302-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:53:24.300-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:53:24.303-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:53:24.326-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.170 seconds
[2024-10-10T04:53:54.697-0400] {processor.py:186} INFO - Started process (PID=83) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:53:54.700-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:53:54.706-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:53:54.705-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:53:54.826-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:53:54.824-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:53:54.826-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:53:54.858-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.171 seconds
[2024-10-10T04:56:37.416-0400] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:56:37.421-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:56:37.427-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:56:37.425-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:56:38.236-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:56:38.221-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:56:38.240-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:56:38.427-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 1.021 seconds
[2024-10-10T04:57:09.168-0400] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:57:09.171-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:57:09.187-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:57:09.185-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:57:10.372-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:57:10.367-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:57:10.373-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:57:10.403-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 1.265 seconds
[2024-10-10T04:57:40.549-0400] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:57:40.553-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:57:40.559-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:57:40.558-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:57:41.042-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:57:41.039-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:57:41.043-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:57:41.070-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.540 seconds
[2024-10-10T04:58:11.544-0400] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:58:11.546-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:58:11.552-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:58:11.551-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:58:11.932-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:58:11.930-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:58:11.932-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:58:11.954-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.423 seconds
[2024-10-10T04:58:42.379-0400] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:58:42.381-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:58:42.399-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:58:42.396-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:58:42.780-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:58:42.779-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:58:42.780-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:58:42.796-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.428 seconds
[2024-10-10T04:59:12.924-0400] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:59:12.926-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:59:12.931-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:59:12.930-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:59:13.304-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:59:13.303-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:59:13.304-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:59:13.325-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.412 seconds
[2024-10-10T04:59:43.534-0400] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:59:43.536-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T04:59:43.541-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:59:43.540-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:59:43.933-0400] {logging_mixin.py:190} INFO - [2024-10-10T04:59:43.932-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T04:59:43.934-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T04:59:43.962-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.447 seconds
[2024-10-10T05:00:14.350-0400] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:00:14.354-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:00:14.359-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:00:14.357-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:00:15.087-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:00:15.085-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:00:15.089-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:00:15.135-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.796 seconds
[2024-10-10T05:01:42.861-0400] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:01:42.868-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:01:42.875-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:01:42.874-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:01:43.805-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:01:43.799-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:01:43.807-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:01:43.873-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 1.034 seconds
[2024-10-10T05:02:14.875-0400] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:02:14.916-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:02:14.954-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:02:14.951-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:02:17.485-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:02:17.478-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:02:17.486-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:02:17.608-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 2.833 seconds
[2024-10-10T05:02:48.169-0400] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:02:48.171-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:02:48.177-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:02:48.175-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:02:48.748-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:02:48.746-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:02:48.748-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:02:48.777-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.617 seconds
[2024-10-10T05:03:19.341-0400] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:03:19.343-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:03:19.348-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:03:19.347-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:03:19.739-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:03:19.738-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:03:19.740-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:03:19.760-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.431 seconds
[2024-10-10T05:03:50.309-0400] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:03:50.312-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:03:50.319-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:03:50.318-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:03:50.703-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:03:50.701-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:03:50.703-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:03:50.726-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.433 seconds
[2024-10-10T05:04:21.216-0400] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:04:21.219-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:04:21.224-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:04:21.223-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:04:21.633-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:04:21.632-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:04:21.634-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:04:21.655-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.454 seconds
[2024-10-10T05:04:51.997-0400] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:04:52.002-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:04:52.029-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:04:52.026-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:04:52.395-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:04:52.393-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:04:52.396-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:04:52.432-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.445 seconds
[2024-10-10T05:05:23.140-0400] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:05:23.143-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:05:23.146-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:05:23.145-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:05:23.228-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:05:23.227-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:05:23.229-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:05:23.256-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.123 seconds
[2024-10-10T05:05:53.372-0400] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:05:53.374-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:05:53.380-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:05:53.378-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:05:53.504-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:05:53.503-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:05:53.505-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:05:53.530-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.175 seconds
[2024-10-10T05:06:23.951-0400] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:06:23.959-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:06:23.965-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:06:23.964-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:06:24.131-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:06:24.129-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:06:24.132-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:06:24.181-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.250 seconds
[2024-10-10T05:06:55.058-0400] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:06:55.063-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:06:55.078-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:06:55.071-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:06:55.230-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:06:55.225-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:06:55.233-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:06:55.262-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.221 seconds
[2024-10-10T05:07:25.852-0400] {processor.py:186} INFO - Started process (PID=83) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:07:25.857-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:07:25.863-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:07:25.862-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:07:25.985-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:07:25.983-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:07:25.985-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:07:26.010-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.186 seconds
[2024-10-10T05:07:56.564-0400] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:07:56.568-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:07:56.576-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:07:56.575-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:07:56.715-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:07:56.713-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:07:56.716-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:07:56.745-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.218 seconds
[2024-10-10T05:08:27.308-0400] {processor.py:186} INFO - Started process (PID=89) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:08:27.311-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:08:27.323-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:08:27.321-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:08:27.429-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:08:27.428-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:08:27.430-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:08:27.468-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.184 seconds
[2024-10-10T05:08:57.757-0400] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:08:57.759-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:08:57.765-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:08:57.764-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:08:57.881-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:08:57.879-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:08:57.882-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:08:57.904-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.159 seconds
[2024-10-10T05:09:28.510-0400] {processor.py:186} INFO - Started process (PID=95) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:09:28.514-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:09:28.520-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:09:28.519-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:09:28.667-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:09:28.665-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'fitz'
[2024-10-10T05:09:28.668-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:09:28.696-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.198 seconds
[2024-10-10T05:09:42.855-0400] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:09:42.859-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:09:42.866-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:09:42.865-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:09:43.017-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:09:43.015-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:09:43.018-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:09:43.051-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.210 seconds
[2024-10-10T05:10:49.642-0400] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:10:49.648-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:10:49.662-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:10:49.661-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:10:50.421-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:10:50.413-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:10:50.423-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:10:50.517-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.897 seconds
[2024-10-10T05:11:21.336-0400] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:11:21.360-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:11:21.437-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:11:21.428-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:11:23.550-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:11:23.546-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:11:23.551-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:11:23.584-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 2.322 seconds
[2024-10-10T05:11:54.101-0400] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:11:54.105-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:11:54.111-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:11:54.110-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:11:54.498-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:11:54.495-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:11:54.498-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:11:54.527-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.438 seconds
[2024-10-10T05:13:16.202-0400] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:13:16.209-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:13:16.222-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:13:16.219-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:13:17.129-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:13:17.122-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:13:17.131-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:13:17.302-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 1.116 seconds
[2024-10-10T05:13:47.979-0400] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:13:47.986-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:13:48.007-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:13:48.001-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:13:49.345-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:13:49.343-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:13:49.346-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:13:49.378-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 1.442 seconds
[2024-10-10T05:14:20.133-0400] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:14:20.137-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:14:20.143-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:14:20.141-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:14:20.754-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:14:20.752-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:14:20.754-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:14:20.774-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.652 seconds
[2024-10-10T05:14:51.419-0400] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:14:51.422-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:14:51.426-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:14:51.425-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:14:51.791-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:14:51.790-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:14:51.792-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:14:51.808-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.399 seconds
[2024-10-10T05:15:21.919-0400] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:15:21.923-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:15:21.950-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:15:21.940-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:15:22.340-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:15:22.339-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:15:22.341-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:15:22.358-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.450 seconds
[2024-10-10T05:15:52.625-0400] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:15:52.628-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:15:52.632-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:15:52.631-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:15:53.043-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:15:53.042-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:15:53.044-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:15:53.063-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.449 seconds
[2024-10-10T05:16:23.579-0400] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:16:23.582-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:16:23.589-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:16:23.587-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:16:24.005-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:16:24.004-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:16:24.006-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:16:24.023-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.454 seconds
[2024-10-10T05:16:54.439-0400] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:16:54.441-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:16:54.446-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:16:54.445-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:16:54.834-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:16:54.833-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:16:54.835-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:16:54.851-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.422 seconds
[2024-10-10T05:17:25.173-0400] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:17:25.176-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:17:25.181-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:17:25.180-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:17:25.318-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:17:25.316-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:17:25.319-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:17:25.341-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.181 seconds
[2024-10-10T05:17:55.840-0400] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:17:55.843-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:17:55.848-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:17:55.847-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:17:55.985-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:17:55.983-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 6, in <module>
    import camelot
ModuleNotFoundError: No module named 'camelot'
[2024-10-10T05:17:55.985-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:17:56.016-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.187 seconds
[2024-10-10T05:18:06.580-0400] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:18:06.586-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:18:06.605-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:18:06.603-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:18:06.729-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:18:06.726-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:18:06.730-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:18:06.764-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.216 seconds
[2024-10-10T05:19:22.590-0400] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:19:22.598-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:19:22.608-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:19:22.607-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:19:23.370-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:19:23.354-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:19:23.373-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:19:23.473-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.902 seconds
[2024-10-10T05:19:53.853-0400] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:19:53.877-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:19:53.905-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:19:53.903-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:19:55.668-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:19:55.663-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:19:55.669-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:19:55.803-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 2.084 seconds
[2024-10-10T05:20:26.441-0400] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:20:26.449-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:20:26.455-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:20:26.454-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:20:26.903-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:20:26.902-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:20:26.904-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:20:26.926-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.495 seconds
[2024-10-10T05:20:57.224-0400] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:20:57.227-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:20:57.231-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:20:57.230-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:20:57.620-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:20:57.618-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:20:57.620-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:20:57.641-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.450 seconds
[2024-10-10T05:22:22.416-0400] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:22:22.437-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:22:22.456-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:22:22.455-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:22:23.235-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:22:23.227-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:22:23.237-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:22:23.356-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.973 seconds
[2024-10-10T05:22:54.314-0400] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:22:54.324-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:22:54.367-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:22:54.363-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:22:55.655-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:22:55.653-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:22:55.656-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:22:55.691-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 1.444 seconds
[2024-10-10T05:23:26.809-0400] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:23:26.817-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:23:26.990-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:23:26.915-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:23:29.076-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:23:29.068-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:23:29.077-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:23:29.173-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 2.479 seconds
[2024-10-10T05:23:59.833-0400] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:23:59.837-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:23:59.849-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:23:59.847-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:24:00.524-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:24:00.521-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:24:00.525-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:24:00.575-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.760 seconds
[2024-10-10T05:24:31.134-0400] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:24:31.138-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:24:31.143-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:24:31.142-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:24:31.540-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:24:31.539-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:24:31.540-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:24:31.558-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.462 seconds
[2024-10-10T05:25:02.058-0400] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:25:02.065-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:25:02.077-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:25:02.075-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:25:02.501-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:25:02.500-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:25:02.501-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:25:02.534-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.486 seconds
[2024-10-10T05:25:32.989-0400] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:25:33.001-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:25:33.012-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:25:33.009-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:25:33.700-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:25:33.699-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:25:33.701-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:25:33.730-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.775 seconds
[2024-10-10T05:26:04.442-0400] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:26:04.447-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:26:04.450-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:26:04.449-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:26:04.539-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:26:04.537-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:26:04.539-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:26:04.571-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.135 seconds
[2024-10-10T05:26:34.751-0400] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:26:34.756-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:26:34.762-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:26:34.760-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:26:34.901-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:26:34.899-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:26:34.902-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:26:34.925-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.185 seconds
[2024-10-10T05:27:05.066-0400] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:27:05.072-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:27:05.077-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:27:05.076-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:27:05.231-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:27:05.229-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:27:05.232-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:27:05.275-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.221 seconds
[2024-10-10T05:27:35.592-0400] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:27:35.594-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:27:35.599-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:27:35.598-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:27:35.745-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:27:35.743-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:27:35.746-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:27:35.767-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.184 seconds
[2024-10-10T05:28:06.112-0400] {processor.py:186} INFO - Started process (PID=83) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:28:06.122-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:28:06.126-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:28:06.125-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:28:06.253-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:28:06.252-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:28:06.254-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:28:06.279-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.177 seconds
[2024-10-10T05:28:36.483-0400] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:28:36.487-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:28:36.493-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:28:36.492-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:28:36.636-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:28:36.633-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:28:36.637-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:28:36.670-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.197 seconds
[2024-10-10T05:29:07.051-0400] {processor.py:186} INFO - Started process (PID=89) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:29:07.054-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:29:07.059-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:29:07.058-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:29:07.188-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:29:07.186-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:29:07.188-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:29:07.231-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.191 seconds
[2024-10-10T05:29:37.812-0400] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:29:37.814-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:29:37.819-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:29:37.818-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:29:37.996-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:29:37.994-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:29:37.997-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:29:38.023-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.221 seconds
[2024-10-10T05:30:08.300-0400] {processor.py:186} INFO - Started process (PID=95) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:30:08.304-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:30:08.309-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:30:08.308-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:30:08.456-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:30:08.453-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:30:08.457-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:30:08.484-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.200 seconds
[2024-10-10T05:30:39.423-0400] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:30:39.435-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:30:39.483-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:30:39.473-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:30:39.788-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:30:39.785-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:30:39.789-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:30:39.827-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.508 seconds
[2024-10-10T05:34:26.263-0400] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:34:26.265-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:34:26.269-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:34:26.269-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:34:26.380-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:34:26.378-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:34:26.380-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:34:26.422-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.172 seconds
[2024-10-10T05:34:56.588-0400] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:34:56.596-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:34:56.603-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:34:56.602-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:34:56.772-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:34:56.770-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:34:56.773-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:34:56.792-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.231 seconds
[2024-10-10T05:35:27.468-0400] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:35:27.472-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:35:27.478-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:35:27.477-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:35:27.566-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:35:27.565-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:35:27.566-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:35:27.585-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.129 seconds
[2024-10-10T05:35:58.069-0400] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:35:58.076-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:35:58.081-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:35:58.080-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:35:58.177-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:35:58.175-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:35:58.177-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:35:58.194-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.140 seconds
[2024-10-10T05:39:26.406-0400] {processor.py:186} INFO - Started process (PID=112) to work on /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:39:26.422-0400] {processor.py:914} INFO - Processing file /opt/airflow/dags/Openai_Pipeline.py for tasks to queue
[2024-10-10T05:39:26.446-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:39:26.445-0400] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:39:26.588-0400] {logging_mixin.py:190} INFO - [2024-10-10T05:39:26.585-0400] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Openai_Pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Openai_Pipeline.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[2024-10-10T05:39:26.589-0400] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Openai_Pipeline.py
[2024-10-10T05:39:26.627-0400] {processor.py:208} INFO - Processing /opt/airflow/dags/Openai_Pipeline.py took 0.243 seconds
